apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: twingate-operator
  namespace: argocd
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: twingate

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  sources:
    # 1) Operator Helm chart from OCI
    - repoURL: ghcr.io/twingate/helmcharts
      chart: twingate-operator
      targetRevision: "0.29.0"  # pin the version
      helm:
        releaseName: twingate-operator
        valueFiles:
          - $values/twingate/operator/values.yaml

    # 2) Git repo source for the values file
    - repoURL: https://github.com/gbern-tg/argocd-example-apps.git
      targetRevision: main
      ref: values
